### ISSUE TITLE
Probably there is an issues with JDK 11

### ISSUE THREAD

**Issue by nkutsche** [nkutsche/xspec-maven-plugin#1]
Using the Plugin with this Maven/JDK:

```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.9.125-linuxkit", arch: "amd64", family: "unix"
```

I get the following error:

```
[ERROR] Failed to execute goal com.nkutsche:xspec-maven-plugin:1.0.1:run-xspec (default) on project docbook-toolchain: Execution default of goal com.nkutsche:xspec-maven-plugin:1.0.1:run-xspec failed: The following error occurred while executing this line:
[ERROR] /bsi/dbt-mvn/target/xspecmaven/build.xml:93: The following error occurred while executing this line:
[ERROR] /bsi/dbt-mvn/target/xspecmaven/xspec-framework/xspec-1.3.0/build.xml:270: Unable to create javax script engine for javascript
```

Needs to check if this is an issue of the XSpec framework or comming from the plugin.

**Comment by AirQuick** [comment]
Will be fixed once xspec/xspec#633 gets resolved. I'll submit a pr soon (to XSpec).

(By the way, I added mention of your plugin to https://github.com/xspec/xspec/wiki/Running-with-Maven)

**Comment by nkutsche** [comment]
@AirQuick great, thanks! saves me time to understand the background of this error.

> (By the way, I added mention of your plugin to https://github.com/xspec/xspec/wiki/Running-with-Maven)

Thanks for that, too! 😃 

PS: I keep this issue open, as I have to update the used XSpec framework version as soon as the initial issue is fixed and released.

**Comment by nkutsche** [comment]
Finally I had time (and the pressure ;-)) to rework this plugin and release it as [version 2.0.0](https://github.com/nkutsche/xspec-maven-plugin/releases/tag/releases%2Fv2.0.0). Now new build in version of XSpec is 1.6.0 but you can [choose newer XSpec versions as plugin dependency](https://github.com/nkutsche/xspec-maven-plugin#xspec-version). This bug is fixed now.
